#!/usr/bin/env bash
#
# Copyright (c) 2015 Joyent Inc., All rights reserved.
#
# Install Ubuntu 14.04 into a directory, modify the installation, then tar it up.
#

set -euo pipefail
IFS=$'\n\t'

INSTALL_DIR=/mnt/chroot
MIRROR=http://archive.ubuntu.com/ubuntu/
GUESTTOOLS=guesttools
NAME="Ubuntu 14.04 LX Brand"
BUILD_DATE=$(date +%Y%m%d)
DOCS="https://docs.joyent.com/images/lx-brand-beta"
TARGET="ubuntu-14.04-lx-${BUILD_DATE}.tar.gz"

echo "==> Installing Ubuntu 14.04 into $INSTALL_DIR"

if [ -d $INSTALL_DIR ]; then
  echo "====> Found previous chroot. Deleting and creating a new one."
  rm -rf $INSTALL_DIR
  mkdir -p $INSTALL_DIR
fi

debootstrap trusty $INSTALL_DIR $MIRROR
echo "==> Done!"

echo "==> Setting locale to en_US.UTF-8"
chroot $INSTALL_DIR locale-gen en_US.UTF-8
chroot $INSTALL_DIR dpkg-reconfigure locales
echo "LANG=\"en_US.UTF-8\"" > $INSTALL_DIR/etc/default/locale

echo "==> Updating $INSTALL_DIR/etc/apt/sources.list"
cat << SOURCES > $INSTALL_DIR/etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu trusty main
deb-src http://archive.ubuntu.com/ubuntu trusty main
deb http://archive.ubuntu.com/ubuntu trusty-updates main
deb-src http://archive.ubuntu.com/ubuntu trusty-updates main
deb http://security.ubuntu.com/ubuntu trusty-security main
deb-src http://security.ubuntu.com/ubuntu trusty-security main
 
deb http://archive.ubuntu.com/ubuntu trusty universe
deb-src http://archive.ubuntu.com/ubuntu trusty universe
deb http://archive.ubuntu.com/ubuntu trusty-updates universe
deb-src http://archive.ubuntu.com/ubuntu trusty-updates universe
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb-src http://security.ubuntu.com/ubuntu trusty-security universe
SOURCES

echo "==> Installing packages..."
chroot $INSTALL_DIR apt-get -y clean
chroot $INSTALL_DIR apt-get -y update
chroot $INSTALL_DIR apt-get -y install openssh-server vim wget curl locales man-db

echo "==> Cleaning up linux-image packages"
chroot $INSTALL_DIR apt-get -y purge linux-image*
chroot $INSTALL_DIR apt-get -y autoremove
chroot $INSTALL_DIR apt-get -y clean


echo "==> Setting TZ to UTC"
rm $INSTALL_DIR/etc/localtime
cp $INSTALL_DIR/usr/share/zoneinfo/UTC $INSTALL_DIR/etc/localtime

echo "==> Disabling PasswordAuthentication"
sed s/PasswordAuthentication\ yes/PasswordAuthentication\ no/ -i $INSTALL_DIR/etc/ssh/sshd_config

echo "==> Creating /etc/motd"
cat << MOTD > $INSTALL_DIR/etc/motd
   __        .                   .
 _|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
  |__|   \`--'  \`-' \`;-| \`-' '  ' \`-'
                   /  ;  Instance ($NAME $BUILD_DATE)
                   \`-'   $DOCS

MOTD

echo "==> Creating /etc/product file"
cat << PRODUCT > $INSTALL_DIR/etc/product
Name: Joyent Instance
Image: $NAME $BUILD_DATE
Documentation: $DOCS
Description: $NAME $BUILD_DATE.
PRODUCT

echo "==> Installing Guest tools in $INSTALL_DIR"
echo "====> Initiallizing and fetching submodule $GUESTTOOLS"
git submodule init
git submodule update --remote
echo "====> Running ./install.sh -i $INSTALL_DIR"
cd $GUESTTOOLS
./install.sh -i $INSTALL_DIR
cd ..

echo "==> Saving installation as $TARGET. This may take a few minutes."
tar czf $TARGET --exclude-from=exclude.txt $INSTALL_DIR/

echo "==> Installation complete!"
echo "==> $TARGET"

exit 0
